name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:7.14.1
        env:
          ELASTICSEARCH_USER: elastic
          ELASTICSEARCH_PASSWORD: xxx
          ELASTICSEARCH_HOST: localhost
          ELASTICSEARCH_PORT: 9200
        ports:
        - "9200:9200"
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run tests
      run: |
        pytest
